require('plugins')
require('plugins.lualine')
require('plugins.comment')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.treesitter-textobjects')
require('plugins.nvim-tree')
require('plugins.which-key')
-- require('plugins.lspinstaller')
require('plugins.lsp.mason')
require('plugins.lsp.lspconfig')
require('plugins.lsp.lspsaga')
require('plugins.nvim-cmp')
require('plugins.vim-test')
require('plugins.alpha')
require('plugins.session-manager')
require('plugins.toggle-term')
require('plugins.harpoon')
-- require('plugins.luasnip')

require('autocmds') -- autocmds must come before options so that Nord bg color is set properly
require('options')
require('mappings')

