[[session]]
name = "neovim config"
path = "~/c/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "tmux config"
path = "~/c/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "dotfiles"
path = "$WORKSPACE/dotfiles/"
startup_command = "nvim"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"
