[[session]]
name = "neovim config"
path = "$WORKSPACE/dotfiles/nvim/"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "$WORKSPACE/dotfiles/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "dotfiles"
path = "$WORKSPACE/dotfiles/"
startup_command = "ls"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"
